// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: thatoneroom/server/v1/service.proto

package serverv1connect

import (
	connect_go "github.com/bufbuild/connect-go"
	_ "github.com/petomalina/thatoneroom/server/pkg/api/thatoneroom/server/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ServerServiceName is the fully-qualified name of the ServerService service.
	ServerServiceName = "thatoneroom.server.v1.ServerService"
)

// ServerServiceClient is a client for the thatoneroom.server.v1.ServerService service.
type ServerServiceClient interface {
}

// NewServerServiceClient constructs a client for the thatoneroom.server.v1.ServerService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &serverServiceClient{}
}

// serverServiceClient implements ServerServiceClient.
type serverServiceClient struct {
}

// ServerServiceHandler is an implementation of the thatoneroom.server.v1.ServerService service.
type ServerServiceHandler interface {
}

// NewServerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerServiceHandler(svc ServerServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	return "/thatoneroom.server.v1.ServerService/", mux
}

// UnimplementedServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerServiceHandler struct{}
