// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file thatoneroom/server/v1/service.proto (package thatoneroom.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service thatoneroom.server.v1.ServerService
 */
export const ServerService = {
  typeName: "thatoneroom.server.v1.ServerService",
  methods: {
  }
} as const;

