// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file thatoneroom/server/v1/service.proto (package thatoneroom.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConnectRequest, ConnectResponse, Request, Response } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service thatoneroom.server.v1.ServerService
 */
export const ServerService = {
  typeName: "thatoneroom.server.v1.ServerService",
  methods: {
    /**
     * @generated from rpc thatoneroom.server.v1.ServerService.Connect
     */
    connect: {
      name: "Connect",
      I: ConnectRequest,
      O: ConnectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc thatoneroom.server.v1.ServerService.Stream
     */
    stream: {
      name: "Stream",
      I: Request,
      O: Response,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

