// @generated by protoc-gen-es v1.2.0
// @generated from file thatoneroom/server/v1/service.proto (package thatoneroom.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum thatoneroom.server.v1.Direction
 */
export const Direction = proto3.makeEnum(
  "thatoneroom.server.v1.Direction",
  [
    {no: 0, name: "UP"},
    {no: 1, name: "DOWN"},
    {no: 2, name: "LEFT"},
    {no: 3, name: "RIGHT"},
    {no: 4, name: "STOP"},
  ],
);

/**
 * @generated from message thatoneroom.server.v1.ConnectRequest
 */
export const ConnectRequest = proto3.makeMessageType(
  "thatoneroom.server.v1.ConnectRequest",
  [],
);

/**
 * @generated from message thatoneroom.server.v1.ConnectResponse
 */
export const ConnectResponse = proto3.makeMessageType(
  "thatoneroom.server.v1.ConnectResponse",
  [],
);

/**
 * @generated from message thatoneroom.server.v1.Request
 */
export const Request = proto3.makeMessageType(
  "thatoneroom.server.v1.Request",
  () => [
    { no: 1, name: "move", kind: "message", T: Move, oneof: "action" },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.Response
 */
export const Response = proto3.makeMessageType(
  "thatoneroom.server.v1.Response",
  () => [
    { no: 2, name: "updateEntity", kind: "message", T: UpdateEntity, oneof: "action" },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.Move
 */
export const Move = proto3.makeMessageType(
  "thatoneroom.server.v1.Move",
  () => [
    { no: 1, name: "direction", kind: "enum", T: proto3.getEnumType(Direction) },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.Entity
 */
export const Entity = proto3.makeMessageType(
  "thatoneroom.server.v1.Entity",
  () => [
    { no: 1, name: "player", kind: "message", T: Player, oneof: "entity" },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.Player
 */
export const Player = proto3.makeMessageType(
  "thatoneroom.server.v1.Player",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "position", kind: "message", T: Coordinate },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.Coordinate
 */
export const Coordinate = proto3.makeMessageType(
  "thatoneroom.server.v1.Coordinate",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "y", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message thatoneroom.server.v1.UpdateEntity
 */
export const UpdateEntity = proto3.makeMessageType(
  "thatoneroom.server.v1.UpdateEntity",
  () => [
    { no: 1, name: "entity", kind: "message", T: Entity },
  ],
);

